### ISSUE TITLE
Constant error

### ISSUE THREAD

**Issue by michaelseto** [bhamon/gpuPlotGenerator#23]
No matter which settings I try, I keep getting the following error (Windows Server 2012 R2 x64) ::

[ERROR][-36][CL_INVALID_COMMAND_QUEUE] Error in step2 kernel finish

nVidia Tesla M60 graphics card

devices.txt :: 0 0 8192 256 8192
start.bat :: gpuPlotGenerator generate buffer x:\18174095959008998309_0_16384000_8192

**Comment by m3talstorm** [comment]
Same on a 1080 ti

> 0 0 11264 256 8192

**Comment by bhamon** [comment]
I suppose you run the plotter on the same GPU you're using to handle your primary display. If so, try to use a lower value for the `hashesNumber` parameter.

@michaelseto: `devices.txt :: 0 0 8192 256 12`
@m3talstorm: `0 0 11264 256 8192 12`

**Comment by bhamon** [comment]
@michaelseto @m3talstorm Can I close this issue?
