### ISSUE TITLE
Output during operation and other questions

### ISSUE THREAD

**Issue by zkdzegede** [bhamon/gpuPlotGenerator#29]
Q1: Can someone place  a screenshot of the expected output during operation?

My final line disappears and sometimes parts of the line reappear.  
I can't tell if my plot is actually still successfully being created.  

I started with 4TB size, moved down several times, now down to 256GB because I don't want to leave it there for a week and then nothing happens.  (That's a week wasted when I could be mining XMR 😛 )

For reference here is what I am using:

I have 5 Nvidia GPUs and an Intel Celeron.  4GB of RAM (more coming in the mail tomorrow)

Q2: Is there something such as 'too many' gpus? 😆 

My devices.txt looks like this

```
0 0 1024 64 8192
0 1 1024 64 8192
0 2 1024 64 8192
0 3 1024 64 8192
0 4 1024 64 8192
```

Anything larger and the plot would fail very quickly. 

Q3: Is there a correlation between how much RAM I need and how much of the GPU I can utilize? 
 
I have a 1080ti in there and it has 11GB, but I can't even use more than 1024 on all the GPUs, when the "setup" command had me input recommended numbers that were several decimal places larger.

**Comment by zkdzegede** [comment]
Screen shot of the missing output line at the bottom. 

![screenshot 2017-12-30 21 32 48_preview](https://user-images.githubusercontent.com/2668400/34454200-86c098d6-eda9-11e7-8a07-de7608806f67.png)

**Comment by zkdzegede** [comment]
Ignoring the ^[[B and ^[[A from me trying to scroll you can see at the end a portion of the line has now appeared with 
```
1.23% (1
```

![screenshot 2017-12-30 21 40 00_preview](https://user-images.githubusercontent.com/2668400/34454218-1b61c0dc-edaa-11e7-924c-a96b13f5d0d4.png)

**Comment by bhamon** [comment]
Q1) You should have the actual generation percent along with technical infos (such as number of nonces generated) and an ETA.
The preallocation step can be really long. Please be sure to launch the plotter as root to have a speed boost on this step.

Q2)Q3)
You can use as many GPUs as you want. But for each GPU the amount of GPU RAM will be reflected as an equal amount of CPU RAM. So, to use the full 11GB of your 1080ti, you'll also need 11GB of RAM on the CPU side.
Please note that there is also an hidden limitation: some graphic cards don't allow to create large aligned buffers in GPU RAM. When you display GPU details, that's the "Max global work size" property.
Using more than one buffer would require a partial rewrite of the OpenCL kernel, but I don't have much free time to spend on this for now.

**Comment by bhamon** [comment]
I just merged the #28 pull request. Maybe it'll correct your display problem.

**Comment by zkdzegede** [comment]
Almost forgot to say...the display problem seems to be fixed.  Thanks.

**Comment by bhamon** [comment]
@zkdzegede Glad to hear it.

The hidden limitation I was talking about is the difference between the "Global memory size" and the "Max memory allocation size".
Your GPU has 8GB of allocatable RAM, but the plotter can't allocate more than 4GB of contiguous RAM inside the OpenCL kernel.
You should be able to use a global work size of 8192 for your GPU.

With the actual memory growth in recent GPUs, it seems like this limitation will be more and more bothersome over time.
If I find some free time I'll work on a multi-buffer version of the OpenCL kernel to bypass this limitation.

**Comment by zkdzegede** [comment]
Ok thank you for the info I'll try it on my next plot!
