### ISSUE TITLE
Setup command infinite output

### ISSUE THREAD

**Issue by littleBro** [bhamon/gpuPlotGenerator#34]
Hello! When I try to run the setup command, it gives just an infinite output, like this:
<img width="427" alt="2018-01-09 13 34 29" src="https://user-images.githubusercontent.com/3585850/34721218-346fd43e-f542-11e7-95e2-81cf1933e96a.png">

And so on, and so on...

**Comment by bhamon** [comment]
Hello @littleBro 
First time I hear of it. Which OS do you use? How do you access to your TTY (remote or local)?
The option is read from the TTY with a standard `std::cin`. It behaves as your input buffer is pre-filled with data.

**Comment by bhamon** [comment]
I close this issue.
Feel free to reopen it if you still experience the problem.
