### ISSUE TITLE
Plotting to Networkdrive ([ERROR] Unable to prevent zero filling: 87)

### ISSUE THREAD

**Issue by zodi1337** [bhamon/gpuPlotGenerator#35]
Hi There!

I really like gpuplotter, thank you for this!

Acutally i'm struggling with direct plots to networkdrives. I would like to plot a file direct from my pc to my servers networkdrive.

My pc runs windows 10, my server (miner) is running debian with samba to share my drives. This is working just fine.
I'm able to map the drive on my windows machine in command prompt using "net use" command. Every time gpuplotgenerator throw the error [ERROR] Unable to prevent zero filling: 87.
On my debian server i tried to format my network drive form EXT4 to NFTS. This is working, but gpuplotgenerator throws the same message.

Mysterious is, the plotfile is allocated on my networkdrive (10GB in my test case). The poltfile is there after try to start the plotter, i see it from my debain and windows machine.

Maybe you see the problem to help me with my problem.
An option to try it without allocating the diskspace before plot could be a workaround. only my thought.

Sorry for my bad english and thank you

**Comment by bhamon** [comment]
Hello @zodi1337 

In your specific configuration Windows can't preallocate a file without 0-filling it as it's a network file and that would be a huge security flaw. It is confirmed in the windows docs [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365544(v=vs.85).aspx) (it is specified as a note under the `hFile` description).

So, two solutions for you:
- Plot on a local drive **with admin rights** to speed things up (the plot files won't be 0-filled the first time they're written to).
- Plot on a network drive **without admin rights** to prevent the plotter to request a SetFileValidData on the file handle. The first writes will be consequently slower.

**Comment by zodi1337** [comment]
Hey @bhamon 

Thank you for the answer.
I didn't tried it to plot without admin rights, but as you have described it should work this way (slower).

My solution will be a fine GPU for my server to avoid ploting to network drives ;)

Thanks, this Issue can be closed from my side
