### ISSUE TITLE
Verification Feature

### ISSUE THREAD

**Issue by TheBigGame117** [bhamon/gpuPlotGenerator#37]
From the readme:

"This command verify overlapping nonces between two plots files. It is usefull to verify a plots file integrity."

This kind of feature really interests me, however the wording seems little scattered, it could be interpreted as two features of the verification.

1. Scans for overlapped nonces - this one's intent easy to interpret however isn't a very difficult thing to avoid on your own.

2. Verify plots intergrity - I interpret that as it will make sure a plot is full of nonces between X and XX, is that the intent of the wording?

My interpretation of the second sentence is what really interests me and I'm hoping for a little clarification. I use GPU plotter more and more now and I'm not stranger to how unstable versions have been in the past and would really like to check to make sure my plots are actually *full* of nonces.

Thanks!

**Comment by bhamon** [comment]
@TheBigGame117 
The `verify` command takes two plots file in input. It determines the overlapping section between the two (in term of plot offset). Every common plots are verified with a binary comparison.

I introduced this command to verify large plot files with smaller samples (in the same plot offset range) when working on the OpenCL kernel to ensure there was no generation error (mostly on the plots files edges).
It also has been used as a mean to verify partially generated plots files. For now this feature lacks the possibility to effectively extract the correctly generated plots or to resume a partially generated plots file.

**Comment by TheBigGame117** [comment]
Well if it accurately tells you if you have a bad plot that's super useful, thanks

**Comment by TheBigGame117** [comment]
Now I just have to figure out how to use it.... I followed your steps up to it actually making it thru cmake... But now I have no idea what to do lol

**Comment by bhamon** [comment]
@TheBigGame117

Let's say you want to check a plots file `<address>_1000_5000_<staggerSize>`.
You can generate smaller plots files to check them against the bigger one (either with my plotter or a CPU one). For example:
```
<address>_1000_1010_10
<address>_2500_2540_40
<address>_4980_5000_20
```

When those files are generated, run the following commands to verify your original plots file:
```shell
./gpuPlotGenerator verify <address>_1000_5000_<staggerSize> <address>_1000_1010_10
./gpuPlotGenerator verify <address>_1000_5000_<staggerSize> <address>_2500_2540_40
./gpuPlotGenerator verify <address>_1000_5000_<staggerSize> <address>_4980_5000_20
```
