### ISSUE TITLE
Program hangs

### ISSUE THREAD

**Issue by yangenhui0** [bhamon/gpuPlotGenerator#39]
my setup: 16G ram ，8Tb wd ，R9 380 4gb  
devices.txt ( 0 0 4096 256 4096  )
useing buffer mode
I can get a constant 40k nonces  
But after a few hours, the program hung up，I can only close the window and start from the beginning.

**Comment by bhamon** [comment]
Can you be more precise about your problem?
Can you output your complete run command?
What is your overall RAM usage? Make sure to use less than 16GB to prevent swapping.
Is your GPU tied to your display? If yes, use a lower `hashesNumber` value (like `4`).

**Comment by yangenhui0** [comment]
run command .\gpuPlotGenerator.exe generate buffer D:\Burst\plots\16790321206628674699_100000000_30490851_8192 E:\Burst\plots\16790321206628674699_200000000_30490851_8192 

the memory is enough.

When  used a 1070 or 1080 with  the same parameters ，it can be successed

I guess my 380 is not good.

**Comment by bhamon** [comment]
It's hard to tell. You can try with lower values as `localWorkSize` and `globalWorkSize` to see if the generation process is more stable.

**Comment by bhamon** [comment]
I close this issue.
Feel free to reopen it if you still experience similar problems.
