### ISSUE TITLE
Output is always broken

### ISSUE THREAD

**Issue by MircoBlitz** [bhamon/gpuPlotGenerator#40]
Hi, this might only be a beauty thing.
From day1 I used this plotter I have an awful output. (see the gif, its made from a realtime screencap, this is as it look always). Could you please make an option where I can say, print it line by line? This would also give me more control, as I can parse the output better with my little fish wrapper.
I am connected to the server by ssh from a Mac Terminal with xterm256 emulation and the plotter is running in a screen session. So there are a couple of layers.

![outputbug-gpuplotter](https://user-images.githubusercontent.com/1020001/35214594-ffb46582-ff61-11e7-9613-4826327a4426.gif)
this gif is realtime.

Thank you very much for your awesome work.

**Comment by bhamon** [comment]
@MircoBlitz Can you try with the latest `4.1.4` version? It should correct your issue.

**Comment by MircoBlitz** [comment]
I would, if i'd could find it :-)

**Comment by bhamon** [comment]
Can you build it from sources (head of the master branch) or do you want a pre-built binary version.
If yes, for which OS?

**Comment by MircoBlitz** [comment]
So it's the actual master branch. No problem, I'll build it right now

**Comment by MircoBlitz** [comment]
I am puzzled, because my git says "everything is to to date" and I pulled about 1 week ago the last time. Did you push?

**Comment by bhamon** [comment]
Yes everything is up to date. Based on d1a3e81ff1c00e678627a0f680f112bb0f9c19ae you should display the `4.1.4` version number while launching the plotter.
I'll push a tag right now but there is no more code change to expect.

**Comment by MircoBlitz** [comment]
Fixed 
Thank you
