### ISSUE TITLE
Program hangs in like 9/10 tries in direct mode and does nothing

### ISSUE THREAD

**Issue by svenerxleben** [bhamon/gpuPlotGenerator#41]
When I try to plot (which works on my computer also only, if I plot a file which has less space than like 1/2 of available ram. Otherwise it plots with like 5 nonces/min or so after 1-2mins) this program hangs on a regular basis. I sometime have to restart 5-10 times in a row until finally some files are generated (sometimes also just one) until i have to restart again.  
Settings:  
devices.txt: 0 0 8192 256 8192
parameter: gpuPlotGenerator.exe generate direct L:\mining\ACCOUNTID_51265710_12000_12000

**Comment by svenerxleben** [comment]
It seems to work when I change my devices.txt to: 0 0 8192 256 16

**Comment by bhamon** [comment]
@svenerxleben Yes, it is a common problem, especially when your GPU is tied to your display (@see my `Troubleshooting` guide).
