### ISSUE TITLE
[ERROR] Unable to open the source file

### ISSUE THREAD

**Issue by v1nsai** [bhamon/gpuPlotGenerator#43]
Not sure what this error means?  I've configured my devices.txt using `gpuPlotGenerator setup` and am getting this error when I run `gpuPlotGenerator generate buffer G:\burst\123456789_7628721_19075408_19075408`

**Comment by bhamon** [comment]
You should have a `kernel` folder besides the `gpuPlotGenerator` binary with the OpenCL kernel files inside.
You can grab them [here](https://github.com/bhamon/gpuPlotGenerator/tree/master/kernel).

**Comment by v1nsai** [comment]
Yea, its even in the github.....how the hell did I manage to delete that?? o_0

Oh well, having issues on Windows made me stop being lazy and set up my much more powerful Linux box with gpuPlotGenerator, so it'll get done much faster anyway.

Thanks for an awesome project!  Once I start mining I'll be sure to send some burst your way.
