### ISSUE TITLE
Performance and Write speed Question

### ISSUE THREAD

**Issue by bhansconnect** [bhamon/gpuPlotGenerator#45]
So I feel like my issue may be related to hardware, but it seems really odd to me and may be software instead.
So at the beginning of direct gpu plotting multiple seagate smr 8tb drives, the gpu is continually at 100% usage and the hdd are writing at about 20-30MB/s per drive. After about 0.5% to 1% of plotting, it suddenly gets really slow. The gpu goes to 0% usage. The drives start to write at about 1-2MB/s per drive. Everything is really slow. After a while, the gpu will spike to 100% for a few seconds and the drives will again be writing at 20-30MB/s per drive. Then, the gpu will fall back to 0% and the drives will be writing really slow. It seems to have a cycle, but the amount of time at 0% or 100% seems random. Sometimes it will cycle every minute or so. Other times it will take it 15-20 min before it spikes to 100% again.
Maybe it is just the SMR drives, but it just seemed really odd to be so I thought I would post the issue and see if you have any ideas about what could be causing the problem.
Thanks for any help and support.

I thought I should add one extra note, the ram fills completely significantly before the plot reaches 0.5% to 1% and the gpu drops to 0% and things slow down.

**Comment by marxsk** [comment]
Seagate SMR drives work fast enough only if they are used for sequential writing. So plot elsewhere and copy it to SMR afterward.

**Comment by bhansconnect** [comment]
I get that smrs are not fast drives, but why at some points would they write at 20-30MB/s and at other points write at like 1-2MB/s. That variance is what makes me question things. Why would they write at a fast speed and max out the gpu for 20 min and then not use the GPU for a long time and write at an utterly slow speed?

**Comment by marxsk** [comment]
@bhansconnect Because they have cache that should solve small amount of random access write. So you are writing to this cache at first. The variance also relies on the data alignment what is (usually) minor issue on traditional HDD but makes big difference on SMR. 

Theoretically, buffer mode should work perfectly as it does write a big piece (few gigs) of sequential data  in the one command. But it did not work that well in reality.

**Comment by bhansconnect** [comment]
Thanks for the quick replies. I guess it really is just the drives. That's too bad, but makes sense. Thanks for the information.

**Comment by bhamon** [comment]
@marxsk Thanks for your quick reply :)
