### ISSUE TITLE
shows CPU memory instead of GPU

### ISSUE THREAD

**Issue by rgjoyce** [bhamon/gpuPlotGenerator#46]
I've tried the latest version and 4.0.3
Same result. my to50Ti has 4Gb memory

C:\Users\Rob\Downloads\gpuPlotGenerator-bin-win-x64-4.0.3>gpuPlotGeneratate buffer d:\plots\13103407935388750190_0_18432000_4096
-------------------------
GPU plot generator v4.0.3
-------------------------
Author:   Cryo
Bitcoin:  138gMBhCrNkbaiTCmUhP9HLU9xwn5QKZgD
Burst:    BURST-YA29-QCEW-QXC3-BKXDL
----
Loading platforms...
Loading devices...
Loading devices configurations...
Initializing generation devices...
    [0] Device: GeForce GTX 1050 Ti (OpenCL 1.2 CUDA)
    [0] Device memory: 512MB
    [0] CPU memory: 512MB
Initializing generation contexts...
    [0] Path: d:/plots/13103407935388750190_0_18432000_4096
    [0] Nonces: 0 to 18431999 (4TB 404GB 0MB)
    [0] CPU memory: 1GB 0MB
----
Devices number: 1
Plots files number: 1
Total nonces number: 18432000
CPU memory: 1GB 512MB
----
Generating nonces...
0.00% (0/18432000 remaining nonces), 0.00 nonces/minutes, ETA: 35y 8w 4d

**Comment by bhamon** [comment]
@rgjoyce The program uses three types of buffer:
- One GPU RAM buffer on each device backed by...
- One CPU RAM buffer of the same size to store the generated nonces.
- One CPU RAM buffer per output file to handle the scoops reordering.

In your case, the process uses 512MB of CPU **and** GPU RAM (nonces buffer) + 1GB CPU RAM (reordering buffer), as described in your output.

To use more of your 4GB GPU RAM, increase the `globalWorkSize` value for this GPU in your `devices.txt` file.

**Comment by rgjoyce** [comment]
Is global work size the last number? My card has 4Gb of memory.
It is already set at 4096. so it can't go higher, right?

**Comment by rgjoyce** [comment]
ok found it.
0 0 4096 1024 4096

Interrupt it without losing what has already been done?
I notice that it's writing to my disk, but the file specified, is still 0 size after a couple of hours.

**Comment by rgjoyce** [comment]
nope. the best I can get out of it is 
0 0 2048 512 2048
result 9-10k per minute
results per row show varying results.
0.06% (10240/18432000 remaining nonces), 9752.38 nonces/minutes, ETA: 1d 7h 2
0.07% (12288/18432000 remaining nonces), 8882.89 nonces/minutes, ETA: 1d 10h
0.07% (12288/18432000 remaining nonces), 8777.14 nonces/minutes, ETA: 1d 10h
0.08% (14336/18432000 remaining nonces), 10119.53 nonces/minutes, ETA: 1d 6h
0.08% (14336/18432000 remaining nonces), 9557.33 nonces/minutes, ETA: 1d 8h 7
0.08% (14336/18432000 remaining nonces), 9452.31 nonces/minutes, ETA: 1d 8h 2
0.08% (14336/18432000 remaining nonces), 8867.63 nonces/minutes, ETA: 1d 10h
0.09% (16384/18432000 remaining nonces), 8330.85 nonces/minutes, ETA: 1d 12h
0.09% (16384/18432000 remaining nonces), 8260.84 nonces/minutes, ETA: 1d 13h
0.10% (18432/18432000 remaining nonces), 9216.00 nonces/minutes, ETA: 1d 9h 1
0.10% (18432/18432000 remaining nonces), 8847.36 nonces/minutes, ETA: 1d 10h
0.10% (18432/18432000 remaining nonces), 8442.14 nonces/minutes, ETA: 1d 12h

**Comment by bhamon** [comment]
@rgjoyce The `globalWorkSize` parameter is the third one. It is expressed in `nonces` (`1 nonce = 4096 * 64 bytes`).

There is no resume feature for now.

**Comment by Quebz** [comment]
Hallo. I need help with divice.txt
Using Asus STRIX 1080ti 11gb
My divice option: 0 0 8192 128 2048
Seams working well 90k nonces/min 
at the start and later stuck 30k ~
Prob not max what i can get...

Approx. Total Memory:       27483 MB
Display Memory (VRAM) : 11127 MB
Shared Memory:                  16356 MB

What should i use in divice.txt setings?

Want optimize my video card for plots
Reduce half of stats from divice.txt 
And plot 2 plots at the same time

**Comment by Quebz** [comment]
Got it working 0 0 8192 128 4
Reducet ram use just 3gb
From 102400 to 4096 in in plot buffer file
Nonces 35k-43k
Plotting 3 plots at a same time
8tb as a single plot. 14h~
Ironfolf 7200rp for seagte propably 20h need to plot
