### ISSUE TITLE
Unable to extend output file when using direct method on NTFS formatted drive

### ISSUE THREAD

**Issue by paupav** [bhamon/gpuPlotGenerator#50]
Whenever I try to create plot with direct method on NTFS partition I get error "Unable to extend output file". 
Plotting on ext4 works fine, as does plotting with buffer method on NTFS partitions.

**Comment by bhamon** [comment]
@paupav This is not an issue in the plotter itself but rather a linux issue regarding it's way to handle the `fallocate` function on NTFS partitions.

**Comment by paupav** [comment]
wouldn't it be fixed easily just by using ntfsfallocate?

**Comment by bhamon** [comment]
`ntfsfallocate` is a binary provided as part of the `ntfs-3g` package. It heavily relies on the `ntfs-3g` driver code. I don't intend to produce a dedicated binary which would embed a partial version of the `ntfsfallocate` code.
